# Generated by Django 5.2.10 on 2026-02-02 16:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[core.validators.validate_cpf]),
        ),
    ]
