# Generated by Django 5.2.10 on 2026-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(default='Litros', max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
