# Generated by Django 5.2.10 on 2026-01-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('MANUTENCAO', 'Manutenção')], default='ATIVA', max_length=15)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_instalacao', models.DateField()),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bombas', to='produtos.produto')),
            ],
        ),
    ]
